### ISSUE TITLE
Use TokenCache in express tooling

### ISSUE THREAD

**Issue by ISO50** [zalando-incubator/authmosphere#169]
@bzums I want to discuss the possible (dis)advantages here.
I've added 2.0.0 flag here, also discussable...

## Pro

- Performance improvement, since we use the cache instead of `getTokenInfo` in [authenticationMiddleware](https://github.com/zalando-incubator/authmosphere/blob/authmosphere-2-0-0-c/src/express-tooling.ts#L169)
- Easier code since we do not need to attach scopes to the `request` object, we could use the cache in [requireScopesMiddleware](https://github.com/zalando-incubator/authmosphere/blob/authmosphere-2-0-0-c/src/express-tooling.ts#L55) to get the Token's scopes.

## Con

* One more APi cahnge, since we need to pass TokenCache into the middlewares.

**Comment by bzums** [comment]
@ISO50 The `TokenCache` is a utility to cache tokens to do requests to other OAuth-secured endpoints without having to issue a new token on each request. 

The use case you describe is about caching the validation results of incoming requests. However, imo we are not allowed to do that since the token can be invalidated at any time (=> security risk)(have to find some resource for that fact). 

So despite the `TokenCache` is not doing the right thing, we should not do it in general I think.

**Comment by ISO50** [comment]
As discussed.
