### ISSUE TITLE
Don't log access token in oauth-middleware

### ISSUE THREAD

**Issue by alex-dellagi** [zalando-incubator/authmosphere#233]
In case of an error, while trying to get the token info from the token info endpoint, the log message can contain the access_token:
Error while getting token info {error: FetchError: request to https://.../tokeninfo?**access_token='here is the real token'** failed, reason: connect ETIMEDOUT ....}

But it should be obfuscated!

https://github.com/zalando-incubator/authmosphere/blob/master/src/express-tooling.ts#L212

**Comment by bzums** [comment]
Hey @alex-dellagi thanks for reporting this! Indeed this sounds like a problem and we should do something about it, however I am not sure how exactly we should tackle this issue since we do not know exactly how the error object looks like (probably also depends on error cause). Any ideas @ISO50 @Retro64 ?
